#!/usr/bin/env ansible-playbook

- name: Gather prerequisites 
  hosts: all
  gather_facts: True
  tasks:
    - name: create groups based on distribution
      group_by: key={{ ansible_distribution }}

- name: Set Hostname
  hosts: Ubuntu
  sudo: True
  tasks:
    - name: Set the hostname to clean-slate
      hostname: name=data-dog

- name: Install Docker
  hosts: Ubuntu
  sudo: True
  vars_prompt:
    - name: "userAccount"
      prompt: "The account to add to the docker group."
      private: no
      default: "ubuntu"
    - name: "composeVersion"
      prompt: "Docker Compose version to install."
      private: no
      default: "1.4.1"

  tasks:
    - debug: msg="userAccount = {{ userAccount }}"
    - debug: msg="composeVersion = {{ composeVersion }}"
    - name: Install cURL
      apt: name=curl state=latest update_cache=true cache_valid_time=600
    - name: Download Docker Installation Script
      command: /usr/bin/curl --location --output /root/install-docker https://get.docker.com/
    - name: Set Permission Bits On The Docker Installation Script
      file: path=/root/install-docker owner=root group=root mode=0500 
    - name: Execute Docker Installation Script
      shell: /root/install-docker 
    - name: Set Memory and Swap Accounting
      lineinfile: dest=/etc/default/grub regexp='^GRUB_CMDLINE_LINUX=""' line='GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1"'
    - name: Add account to the docker group 
      user: name={{ userAccount }} groups=docker 
    - name: Restart Docker
      command: service docker restart
    - name: Test Docker
      command: docker run hello-world
    - name: Download Docker Compose Script
      shell: /usr/bin/curl --location --output /usr/local/bin/docker-compose https://github.com/docker/compose/releases/download/{{ composeVersion }}/docker-compose-`uname -s`-`uname -m`
    - name: Set Permission Bits On The Docker Compose Script
      file: path=/usr/local/bin/docker-compose owner=root group=root mode=0555
    - name: Echo Docker Compose version
      command: docker-compose --version

- name: Install Git
  hosts: Ubuntu
  sudo: True
  tasks:
    - name: Install Git
      apt: name=git state=latest update_cache=true cache_valid_time=600

- name: Install Git Projects
  hosts: Ubuntu
  sudo: False
  tasks:
    - name: Make GitHub Directory
      file: path={{ ansible_env.HOME }}/GitHub state=directory mode=0755
    - name: Pull Down Monitoring Infrastructure
      git: repo=https://github.com/kurron/docker-monitor-compose.git dest={{ ansible_env.HOME }}/GitHub/docker-monitor-compose
    - name: Pull Down Data Pump 
      git: repo=https://github.com/kurron/docker-monitor-jmeter.git dest={{ ansible_env.HOME }}/GitHub/docker-monitor-jmeter

- name: Update Hosts File 
  hosts: Ubuntu
  sudo: True
  tasks:
    - name: Add MongoDB entry 
      lineinfile: dest=/etc/hosts line="127.0.0.1 mongodb" 
    - name: Add Redis entry 
      lineinfile: dest=/etc/hosts line="127.0.0.1 redis" 
    - name: Add MySQL entry 
      lineinfile: dest=/etc/hosts line="127.0.0.1 mysql" 
    - name: Add PostgreSQL entry 
      lineinfile: dest=/etc/hosts line="127.0.0.1 postgresql" 
    - name: Add RabbitMQ entry 
      lineinfile: dest=/etc/hosts line="127.0.0.1 rabbitmq" 

- name: Configure Rsyslog To Forward to Loggly
  hosts: Ubuntu
  sudo: True
  vars_prompt:
    - name: "logglyKey"
      prompt: "The Loggly API key to use."
      private: no
      default: "91ec9498-62c1-42fc-b9e9-a977628cb17d"
    - name: "logglyTag"
      prompt: "The Loggly Tag to use."
      private: no
      default: "data-dog"
  tasks:
    - debug: msg="logglyKey = {{ logglyKey }}"
    - debug: msg="logglyPath = {{ logglyTag }}"
    - name: Copy Rsyslog Configuration File 
      template: src=templates/loggly.conf dest=/etc/rsyslog.d/22-loggly.conf mode=0444 backup=yes force=yes
    - name: Restart the Rsyslog
      command: /usr/sbin/service rsyslog restart
    - name: Send a test message 
      command: logger 'Hello From Ansible!'

- name: Install Data Dog
  hosts: Ubuntu
  sudo: True
  vars_prompt:
    - name: "dataDogKey"
      prompt: "The Data Dog API Key to use."
      private: no
      default: "4a2ad6741d78c9f690510083065a0bff"
  tasks:
    - debug: msg="dataDogKey = {{ dataDogKey }}"
    - name: Run the datadog installation script
      shell: DD_API_KEY={{ dataDogKey }} bash -c "$(curl -L https://raw.githubusercontent.com/DataDog/dd-agent/master/packaging/datadog-agent/source/install_agent.sh)"
    - name: Add account to the docker group 
      user: name=dd-agent groups=docker 
    - name: Copy Docker configuration file 
      copy: src=files/docker.yaml dest=/etc/dd-agent/conf.d/docker.yaml owner=dd-agent group=root mode=0444
    - name: Copy RabbitMQ configuration file
      copy: src=files/rabbitmq.yaml dest=/etc/dd-agent/conf.d/rabbitmq.yaml owner=dd-agent group=root mode=0444
    - name: Restart the agent
      service: name=datadog-agent state=restarted 
