#!/usr/bin/env ansible-playbook

- name: Gather prerequisites 
  hosts: all
  gather_facts: True
  tasks:
    - name: create groups based on distribution
      group_by: key={{ ansible_distribution }}

- name: Install Docker
  hosts: Ubuntu
  sudo: True
  vars_prompt:
    - name: "userAccount"
      prompt: "The account to add to the docker group."
      private: no
      default: "vagrant"

  tasks:
#   - debug: msg="notablescan = {{ notablescan }}"
    - name: Install wget
      apt: name=wget state=latest update_cache=true cache_valid_time=600
    - name: Install cURL
      apt: name=curl state=latest update_cache=true cache_valid_time=600
    - name: Download Docker Installation Script
#     get_url: url=https://get.docker.com/ dest=/root/install-docker mode=0550
      command: /usr/bin/curl --output /root/install-docker https://get.docker.com/
    - name: Set Permission Bits On The Docker Installation Script
      file: path=/root/install-docker owner=root group=root mode=0500 
    - name: Execute Docker Installation Script
      shell: /root/install-docker 
    - name: Set Memory and Swap Accounting
      lineinfile: dest=/etc/default/grub regexp='^GRUB_CMDLINE_LINUX=""' line='GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1"'
    - name: Add account to the docker group 
      user: name={{ userAccount }} groups=docker 
    - name: Restart Docker
      command: service docker restart

#   - name: Set the permissions on the specified data directory
#     file: path={{ dbPath }} owner=mongodb group=mongodb mode=0775 state=directory 
#   - name: Restart MongoDB 
#     service: name=mongod state=restarted
